### ISSUE TITLE
Make it more visible that the default class is the first level

### ISSUE THREAD

**Issue by ad1729** [topepo/yardstick#13]
Hi Max,

Thanks for making this useful package! I have a suggestion:

Taking the first level of response as the class of interest can lead to problems since most (in my limited experience) binary problems use the {0,1} or {-1,1} encoding for the response variable where `1` denotes the class of interest. It should be mentioned in the `README.md` just so that people are aware that  by default it ends up taking class 0 as the class of interest, and they can use the `options(yardstick.event_first = FALSE)` to disable this behaviour.

An example of the possible errors it can lead to are the precision/recall numbers [in this article.](http://www.business-science.io/business/2017/11/28/customer_churn_analysis_keras.html)

Perhaps it might be better to set the default value for `yardstick.event_first` to `FALSE` and allow the user to override it to `TRUE` in case their response uses the lower level value to denote the class of interest?

Regards,

Akshat

**Comment by mdancho84** [comment]
Thanks for the excellent package. I have since updated the [Keras Churn Analysis Article](http://www.business-science.io/business/2017/11/28/customer_churn_analysis_keras.html) to reflect the correct precision and recall using `options(yardstick.event_first = FALSE)`. I agree that this is not intuitive as most classification metrics in other packages (e.g. `h2o`) reflect 1 being the positive class. Defaulting `yardstick` to 1 as class of interest is a good suggestion.

**Comment by topepo** [comment]
I see your point but, in R at least, it is anathema to encode your outcome numerically when it is qualitative data. The vast majority of classification functions use factors to store the outcome data. In that context, why would the _last_ level of the factor be the most important? 

Let me think about it some more though. One other issue is that you almost never get emails from people saying "I'm glad that your default is _X_" so it is hard to tell if more people would be pissed if I change it.

Either way, it would be a good idea to say something like "fyi the first class is the event of interest. change it using..." on startup. 

@mdancho84 I was going to drop you guys a note today anyway; I used your [time series post](http://www.business-science.io/code-tools/2017/10/25/demo_week_sweep.html) as an example in the [`rsample` vingettes](https://topepo.github.io/rsample/articles/Applications/Time_Series.html). Let me know if you see any issues with it.

**Comment by mdancho84** [comment]
Ok. See your point as well. The clarification may be a best of both worlds solution. 

Nice! I’ll check out the vignette. Time series is a common analysis that gets messed up. Glad you are thinking about it. Looking forward to reviewing.

**Comment by mdancho84** [comment]
Looks awesome! I still need to run the code but outstanding if it works as shown!

**Comment by ad1729** [comment]
Thanks for your reply, I didn't think of factor outcomes. Perhaps something like a print statement when recall/precision/summary functions are called that output (for example)

```
Using class `level(response)[1]` as the class of interest.
```

followed by the computed metrics? Alternatively, a package startup message could work but I'm not sure if it would show up when someone calls the function using the double colon (`::`) operator.

**Comment by topepo** [comment]
I don't want to add additional printing. Once people start resampling that that becomes a pain. 

I hate seeing package startup messages and, for that reason, it would stick in peoples head that there is a decision to make and what the default is. 

If someone knows to call by namespace, they would have most likely loaded the package and been annoyed by the startup message (and so they will remember it). 

I'll definitely add something to the print method for `cond_mat` to denote what value was used and will adjust the tidy methods too.

**Comment by ad1729** [comment]
Fair enough. Thanks for the discussion!

**Comment by mdancho84** [comment]
Max,
Nice work on `rsample`. I've started using it in my [rsample testing repo](https://github.com/mdancho84/rsample_testing). 

My recreation of your time series article is [here](https://github.com/mdancho84/rsample_testing/blob/master/rsample_time_series.md). It follows my style of coding, but for the most part, does the same thing. Really enjoyed using `rsample`. I'm looking forward to using it for cross validation and bootstrap resampling in my machine learning endeavors. It makes things so much easier.  

Regarding the Time Series Analysis Example, there's one minor change you may want to implement to let the "start" parameter of the ts object adjust with the start of the analysis() set. 
```
fit_model <- function(x, ...) {
  mod_dat <- tk_ts(analysis(x), start = 1992, freq = 12)
  auto.arima(mod_dat)
}
```
Consider this.
```
fit_model <- function(x, ...) {
    x %>%
        analysis() %>%
        tk_ts(start  = .$date[[1]] %>% as.yearmon(), 
              freq   = 12, 
              silent = TRUE) %>%
        auto.arima(...)
}
```
Other than that, I had no problem following and thoroughly enjoyed the example. You will likely end up seeing a blog post using `rsample` soon. 
-Matt

**Comment by topepo** [comment]
Good! I took that code and [added it](https://topepo.github.io/rsample/articles/Applications/Time_Series.html) (I've never been a time series guy)

Let me know if you have any feature requests for `rsample`.  I'm mostly interested in getting old-school bootstrap analysis into it next year.

**Comment by mdancho84** [comment]
Looks great! Time series is certainly an area that a lot of people have questions on. I'm really happy with the `rolling_origin()` function. 

Grid Search and Cross Validation are two big areas. I'll hit you up via email with some dialog on ideas.
